[build]	
    base = "site
    command = "npm run build"
    publish = "public"
    build = "build"

[build.environment]	
    NODE_ENV = "development"	

[context.production.environment]	
    NODE_ENV = "production"